select
    source_key as transaction_id,
    transaction_date,
    nullif(trim(customer_name), '') as customer_name,
    nullif(trim(reference_number), '') as reference_number,
    description,
    category,
    quantity,
    weight_kg,
    tax,
    rate,
    coalesce(amount_due, 0)::numeric as amount_due,
    coalesce(amount_received, 0)::numeric as amount_received,
    coalesce(balance, 0)::numeric as source_balance,
    source_workbook,
    source_sheet,
    source_row,
    ingested_at,
    coalesce(transaction_type, 'UNKNOWN') as transaction_type,
    classification_reason,
    date_status,
    quality_flags,
    coalesce(is_realized_transaction, false) as is_realized_transaction,
    ledger_effect
from {{ source('raw', 'customer_transactions') }}
